### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by michaelaye** [jjlee/mechanize#104] opened 2015-01-16 20:10 UTC
First time using, installed with pip, I get this:
```python
import mechanize
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6b82e40e2c8e> in <module>()
----> 1 import mechanize

/Users/maye/miniconda3/envs/py34/lib/python3.4/site-packages/mechanize/__init__.py in <module>()
    117 import sys
    118 
--> 119 from _version import __version__
    120 
    121 # high-level stateful browser-style interface

ImportError: No module named '_version'
```

**Comment by cswarren** [comment] 2015-04-13 15:27
Is this using Python 3? If so, this is a duplicate of #96.

**Comment by michaelaye** [comment] 2015-04-13 16:06
As above path indicates, yes it was.

**Closed** 2015-04-13 16:08 UTC
